# Generated by Django 4.2.11 on 2024-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='', max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
